[tool.poetry]
name = "juegosferrando"
version = "0.1.0"
description = "juegos en python"
authors = ["FJET"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
